trigger:
  - main # Or your default branch
pool:
  vmImage: 'windows-latest'
steps:
  - task: CopyFiles@2
    inputs:
      SourceFolder: 'scripts'
      Contents: '**/*.ps1'
      TargetFolder: '$(Build.ArtifactStagingDirectory)/scripts'
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/scripts'
      ArtifactName: 'Scripts'
